name: .NET Build

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - uses: nuget/setup-nuget@v1
    - run: nuget restore SnaffPoint.sln
    - name: Install PnP
      run: dotnet add package PnP.Core
    - name: Build
      run: dotnet build --configuration Release
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - name: Create Release
      id: create_release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: Release ${{ github.sha }}
        files: ./SnaffPoint/bin/Release/SnaffPoint.exe
        prerelease: false
